# Generated automatically from Makefile.in by configure.
#Path of MPI-Library on the Machine

MPI_DIR     = $(HOME)/OpenMPI
MPI_INC_DIR = $(MPI_DIR)/include
MPI_BIN_DIR = $(MPI_DIR)/bin
MPI_LIB_DIR = $(MPI_DIR)/lib

ATF_DIR      = $(HOME)/ATF/trunk
ATF_BIN_DIR  = $(ATF_DIR)/bin
ATF_INC_DIR  = $(ATF_DIR)/include
ATF_LIB_DIR  = $(ATF_DIR)/lib

#Set some Flags
AR	    = ar
AR_FLAGS    = clr 

CC          = mpicc
CFLAGS      = -ansi -Wall -g -I$(ATF_INC_DIR)
LDFLAGS     = -lm 

FC          = mpif77
FFLAGS      = -g -I${ATF_INC_DIR)
FLDFLAGS    = -lm

EXE         = ATF

