# Generated automatically from Makefile.in by configure.
#Path of MPI-Library on the Machine

MPI_DIR     = /opt/mpich2-ssm
MPI_INC_DIR = /opt/mpich2-ssm/include
MPI_BIN_DIR = /opt/mpich2-ssm/bin
MPI_LIB_DIR = /opt/mpich2-ssm/lib

ADCL_DIR      = /home/Arthur/ADCL/trunk
ADCL_BIN_DIR  = /home/Arthur/ADCL/trunk/bin
ADCL_INC_DIR  = /home/Arthur/ADCL/trunk/include
ADCL_LIB_DIR  = /home/Arthur/ADCL/trunk/lib

ADCL_LIB      = libadcl.a

#Set some Flags
AR	    = ar
AR_FLAGS    = clr


CC          = $(MPI_BIN_DIR)/mpicc
CFLAGS      = -g -O2 -I$(ADCL_INC_DIR)
LDFLAGS     =  -L$(ADCL_LIB_DIR) -ladcl -lm 

FC          = $(MPI_BIN_DIR)/mpif90
FFLAGS      = -g -O2 -I$(ADCL_INC_DIR)
FLDFLAGS    =  -L$(ADCL_LIB_DIR) -ladcl -lm

