include ../Makefile.defs

colltest : *.c
	$(CC) -c   colltest.c     -DGLOBAL $(CFLAGS) 
	$(CC) -c   allgather.c      -DGLOBAL $(CFLAGS) 
	$(CC) -c   allreduce.c      -DGLOBAL $(CFLAGS) 
	$(CC) -c   alltoall.c       -DGLOBAL $(CFLAGS) 
	$(CC) -c   barrier.c        -DGLOBAL $(CFLAGS) 
	$(CC) -c   bcast.c          -DGLOBAL $(CFLAGS) 
	$(CC) -c   reduce.c         -DGLOBAL $(CFLAGS) 
	$(CC) -c   reducescatter.c  -DGLOBAL $(CFLAGS) 
	$(CC) -c   gather.c         -DGLOBAL $(CFLAGS) 
	$(CC) -c   scatter.c        -DGLOBAL $(CFLAGS) 
	$(CC) -c   scan.c           -DGLOBAL $(CFLAGS) 
	$(CC) -o   colltest *.o $(CFLAGS)  $(LDFLAGS)

#C-Test-Routines for global operations 

allgather: allgather.c
	$(CC) -o allgather allgather.c  $(CFLAGS)  $(LDFLAGS)

allreduce: allreduce.c
	$(CC) -o allreduce allreduce.c  $(CFLAGS) $(LDFLAGS)

alltoall: alltoall.c
	$(CC) -o alltoall alltoall.c  $(CFLAGS)  $(LDFLAGS)

barrier: barrier.c
	$(CC) -o barrier barrier.c  $(CFLAGS)  $(LDFLAGS) 

bcast: bcast.c
	$(CC) -o bcast bcast.c  $(CFLAGS) $(LDFLAGS) 

reduce: reduce.c
	$(CC) -o reduce reduce.c  $(CFLAGS) $(LDFLAGS) 

reducescatter: reducescatter.c
	$(CC) -o reducescatter reducescatter.c  $(CFLAGS) $(LDFLAGS) 

gather: gather.c
	$(CC) -o gather gather.c  $(CFLAGS)  $(LDFLAGS)  

scatter: scatter.c
	$(CC) -o scatter scatter.c  $(CFLAGS) $(LDFLAGS) 

scan: scan.c 
	$(CC) -o scan scan.c $(CFLAGS)  $(LDFLAGS) 

clean:
	$(RM) *.o *~ 
	$(RM) colltest allgather allreduce alltoall barrier bcast reduce reducescatter gather scatter scan

