#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "minmax.h"

int numprocs=-1, numrequests=-1, nummethods=-1, nummeas=-1;
FILE **infd=NULL,  *outfd=NULL, *allredfd=NULL;

int main (int argc, char **argv )
{
    int i, ret, all_done, no_line,  iter;
    int allredcnt=0;
    char line[MAXLINE];
    double time;
    struct lininf tline;
    struct procinf *tproc;


    minmax_init ( argc, argv, NULL );

    /* Read infile and store the values in the according list */
    TLINE_INIT(tline);
    all_done = 0;
    while ( all_done < numprocs ) {
	
	for ( i=0; i< numprocs; i++ ) {
	    no_line = 0;
	    while ( !no_line ) {
		ret = fscanf ( infd[i], "%[^\n]\n", line );
		if ( EOF == ret ) {
		    all_done++;
		    break;
		}
		if ( line[0] == '#' ) {
		    /* Skip comment lines */
		    continue;
		}
		no_line = 1;
	    }	    
	    
	    if ( allredcnt == 6 ) {
		sscanf ( line, "%d %lf\n", &iter, &time );
	    }
	    else {
		sscanf ( line, "%lf\n", &time );
	    }		
		
	    TLINE_MIN(tline,time,i);
	    TLINE_MAX(tline,time,i);

	}
	
	if ( allredcnt == 6 ) {
	    fprintf (outfd, 
		     "%3d %8.4lf %3d %8.4lf %3d\n", 
		     numrequests * iter, 
		     tline.min * 1000000, 
		     tline.minloc,
		     tline.max * 1000000, 
		     tline.maxloc );
	}
	else {
	    fprintf( allredfd, "%8.4lf %3d %8.4lf %3d\n", 
		     tline.min * 1000000, 
		     tline.minloc,
		     tline.max * 1000000, 
		     tline.maxloc );
	}		     

	tproc[tline.minloc].nummin++;
	tproc[tline.maxloc].nummax++;

	/* Reset the lininf structure */
	TLINE_INIT(tline);
	if ( allredcnt == 6 )
	    allredcnt = 0;
	else 
	    allredcnt++;
    }
    

    for ( i=0; i< numprocs; i++ ) {
	fclose ( infd[i]);
    }
    fclose ( outfd );
    fclose ( allredfd );
    free ( tproc );
    free ( infd );

    return ( 0 );
}


/**********************************************************************/
/**********************************************************************/
/**********************************************************************/
void minmax_init (int argc, char ** argv, struct procinf **proc) 
{
    struct procinf *tproc;
    char inname[50];
    int i;


    if (argc < 5 )
    {
	printf(" Usage : iterations <numprocs> <numrequests> <nummethods> <nummeas>"
	       " <options>\n\n");
	printf("   minmax takes the output files generated by ADCL and \n");
	printf("   determines for each individual measurement the minimal and \n");
	printf("   maximual value across all processes and the according locations\n");
	printf(" Options: \n");
	printf("   <numprocs>   : number of processes \n");
	printf("   <numrequests>: number of requests \n");
	printf("   <nummethods> : number of evaluated implementations \n");
	printf("   <nummeas>    : number of measurements per implementation \n");
	exit ( 1 ) ;
    }
    
    numprocs    = atoi( argv[1] );
    numrequests = atoi ( argv[2] );
    nummethods  = atoi (argv[3] );
    nummeas     = atoi ( argv[4]);
    


    tproc = (struct procinf *) calloc (1, numprocs * sizeof(struct procinf));
    if ( NULL == tproc ) {
	exit ( -1 );
    }
    *proc = tproc;

    infd = (FILE **) malloc ( numprocs * sizeof(FILE *) );
    if ( NULL == infd ) {
	exit (-1);
    }

    outfd = fopen ("iterations.out", "w");
    if ( NULL == outfd ) {
	exit ( -1 );
    }

    allredfd = fopen ("allreduce.out", "w");
    if ( NULL == allredfd ) {
	exit ( -1 );
    }
    


    for ( i = 0; i < numprocs; i++ ) {
	sprintf( inname, "%d_app.out", i);
	infd[i] = fopen ( inname, "r" );
    }	

    return;
}
